
export const auth = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_AUTHORIZE_SUCCESS: 'AUTH_AUTHORIZE_SUCCESS',
  AUTH_AUTHORIZE_ERROR: 'AUTH_AUTHORIZE_ERROR',
  AUTH_AUTHORIZE_PENDING: 'AUTH_AUTHORIZE_PENDING',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  AUTH_REGISTER_PENDING: 'AUTH_REGISTER_PENDING',
}

export const users = {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_PENDING: 'GET_USERS_PENDING',
}

export const translation = {
  GET_TRANSLATION_SUCCESS: 'GET_TRANSLATION_SUCCESS',
  GET_TRANSLATION_ERROR: 'GET_TRANSLATION_ERROR',
  GET_TRANSLATION_PENDING: 'GET_TRANSLATION_PENDING',
  CREATE_TRANSLATION_SUCCESS: 'CREATE_TRANSLATION_SUCCESS',
  CREATE_TRANSLATION_ERROR: 'CREATE_TRANSLATION_ERROR',
  CREATE_TRANSLATION_PENDING: 'CREATE_TRANSLATION_PENDING',
}
